/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-surface": "#1a1c1d",
        "tertiary-container": "#1b1b1e",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-highest": "#e2e2e3",
        "surface-container-high": "#e8e8e9",
        "surface-container-low": "#f3f3f4",
        "on-surface-variant": "#4c4546",
        "on-primary-container": "#848484",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3132",
        "on-tertiary-container": "#848387",
        "tertiary-fixed-dim": "#c8c6c9",
        "on-primary-fixed-variant": "#474747",
        "error": "#ba1a1a",
        "on-secondary-container": "#63646c",
        "on-tertiary-fixed": "#1b1b1e",
        "on-error": "#ffffff",
        "surface-container": "#eeeeef",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#46464e",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#47464a",
        "surface-dim": "#dadadb",
        "on-error-container": "#93000a",
        "outline": "#7e7576",
        "surface-variant": "#e2e2e3",
        "primary": "#000000",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed": "#1a1b22",
        "secondary": "#5d5e66",
        "on-secondary": "#ffffff",
        "surface": "#f9f9fa",
        "surface-bright": "#f9f9fa",
        "outline-variant": "#cfc4c5",
        "inverse-primary": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "on-background": "#1a1c1d",
        "tertiary-fixed": "#e4e1e5",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1b1b1b",
        "secondary-fixed": "#e3e1ec",
        "secondary-fixed-dim": "#c6c5cf",
        "background": "#f9f9fa",
        "secondary-container": "#e3e1ec",
        "emerald-success": "#10B981"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "base": "4px",
        "unit-1": "0.25rem",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "unit-8": "2rem",
        "gutter": "24px",
        "unit-12": "3rem",
        "unit-2": "0.5rem",
        "unit-4": "1rem"
      },
      "fontFamily": {
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "table-data": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "display": ["Hanken Grotesk"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "table-data": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
